import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const valor = Math.floor(Math.random() * 20);
  return (
    <html lang="en">
      <body>
        <nav className="bg-red-600">
          <ul>
            <li>{valor}</li>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/dashboard">Dashboard</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
