import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GenerateMenu from "./components/AllLayouts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GenerateMenu />
      <body>{children}</body>
    </html>
  );
}
