import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navigation from './components/Navigation'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const navLinks = [
    {
      name: 'Home',
      href: '/',
    },
    {
      name: 'DashBoard',
      href: '/dashboard',
    },
    {
      name: 'Blog',
      href: '/blog',
    }
  ]
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Navigation navLinks={navLinks} />
        {children}
        </body>
    </html>
  )
}
